# Generated by Django 5.2.13 on 2026-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0011_alter_dia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="palco",
            name="acessibilidade_mobilidade_reduzida",
            field=models.BooleanField(default=True),
        ),
    ]
